apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "apm.fullname" . }}-oauth2"
  labels:
    {{- include "apm.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
data:
  APM_UI: {{ printf "https://%s-jaeger.%s.%s" (include "apm.fullname" .) .Release.Namespace .Values.ingress.domain  | b64enc }}
  APM_SERVER: {{  printf "http://%s-otel-collector:4318" (include "apm.fullname" .) | b64enc }}
