{{- $serviceName := include "pulumi-stack.serviceName" .}}
---
apiVersion: pulumi.com/v1
kind: Stack
metadata:
  name: {{ printf "%s-%s" .Release.Namespace $serviceName | trunc 63 | trimSuffix "-" }}  
  namespace: pulumi-operator
  labels:
    {{- include "pulumi-stack.labels" . | nindent 4 }}
spec:
  backend: 's3://pulumi-backend?endpoint=https://shared-clients-api.minio.beta.stack.io&s3ForcePathStyle=true'
  envRefs:
    PULUMI_CONFIG_PASSPHRASE:
      type: Secret
      secret:
        name: pulumi-secrets
        key: PULUMI_CONFIG_PASSPHRASE
    AWS_ACCESS_KEY_ID:
      type: Secret
      secret:
        name: pulumi-secrets
        key: AWS_ACCESS_KEY_ID
    AWS_SECRET_ACCESS_KEY:
      type: Secret
      secret:
        name: pulumi-secrets
        key: AWS_SECRET_ACCESS_KEY
    AWS_DEFAULT_REGION:
      type: Secret
      secret:
        name: pulumi-secrets
        key: AWS_DEFAULT_REGION
    MINIO_USER:
      type: Secret
      secret:
        name: pulumi-secrets
        key: MINIO_ACCESS_KEY
    MINIO_PASSWORD:
      type: Secret
      secret:
        name: pulumi-secrets
        key: MINIO_SECRET_KEY
    MINIO_ENDPOINT:
      type: Secret
      secret:
        name: pulumi-secrets
        key: MINIO_ENDPOINT
    MINIO_ENABLE_HTTPS:
      type: Secret
      secret:
        name: pulumi-secrets
        key: MINIO_ENABLE_HTTPS
  stack: "{{ .Release.Namespace }}.{{ include "pulumi-stack.serviceName" . }}.minio.bucket.stack"
  projectRepo: https://github.com/vmfarms/pulumi-minio-stack
  branch: feat/bucket-acl
  config:
    aws:region: us-east-1
    pulumi-s3-python:Name: {{ include "pulumi-stack.serviceName" . }}
    pulumi-s3-python:Namespace: {{ .Release.Namespace }}
    pulumi-s3-python:ReleaseName: {{ .Release.Name }}
    pulumi-s3-python:Policy: {{ .Values.Policy }} 
